//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MQTTSubscribeProject
{
    using System;
    using HP.ST.Fwk.RunTimeFWK;
    
    
    public partial class MQTTSubscribe
    {
        
        private string _mqttbroker;
        
        private string _mqttusername;
        
        private string _mqttpassword;
        
        private string _mqtttopic;
        
        private string _mqttmessage;
        
        private string _name;
        
        //  InputProperties Section
        [Report()]
        public virtual string MQTTBroker
        {
            get
            {
                return this._mqttbroker;
            }
            set
            {
                this._mqttbroker = value;
            }
        }
        
        [Report()]
        public virtual string MQTTUsername
        {
            get
            {
                return this._mqttusername;
            }
            set
            {
                this._mqttusername = value;
            }
        }
        
        [Report()]
        public virtual string MQTTPassword
        {
            get
            {
                return this._mqttpassword;
            }
            set
            {
                this._mqttpassword = value;
            }
        }
        
        [Report()]
        public virtual string MQTTTopic
        {
            get
            {
                return this._mqtttopic;
            }
            set
            {
                this._mqtttopic = value;
            }
        }
        
        //  OutputProperties Section
        [Report()]
        public virtual string MQTTMessage
        {
            get
            {
                return this._mqttmessage;
            }
            set
            {
                this._mqttmessage = value;
            }
        }
        
        //  GeneralProperties Section
        [Report()]
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
    }
}
